### ISSUE TITLE
About the CSS body font size

### ISSUE THREAD

**Issue by wenhao219** [dawoodsa/react-text-animations#3]
Hi, the issue I'm facing now is while every time I compile my project, the library CSS will change my body font size to 4rem. I want to ask do you have any method to let the library CSS won't overwrite my CSS. Thank you.

**Comment by dawoodsa** [comment]
Hi, wenhao, I fixed the bug and should be working fine now.
It was as you said, that I declared `font-size: 4rem` for the whole body.
Just update the package by running `npm i react-text-animations` and your good to go.
please reply with how it turns out so I can close the issue, thank you.

**Comment by wenhao219** [comment]
Now the body font size is ok, thank you for your help.
